"""Initial migration

Revision ID: 28007452ad42
Revises: 
Create Date: 2024-04-03 17:59:56.834880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28007452ad42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=False, comment='Фамилия'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('patronymic', sa.String(length=100), nullable=True, comment='Отчество'),
    sa.Column('date_birth', sa.Date(), nullable=False, comment='Дата рождения'),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('is_ban', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('license_plate_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('paytype')
    # ### end Alembic commands ###
